apiVersion: external-secrets.io/v1
kind: SecretStore
metadata:
  name: oci-instance-principal
spec:
  provider:
    oracle:
      vault: ocid1.vault.oc1.eu-frankfurt-1.enu5etitaacsw.abtheljthp4lxmv4joecvha6upatkxfii3hilblyvuf4ij4zft2bsi4zakia
      principalType: InstancePrincipal
