global:
  domain: argocd.k8s1.christiank.dev
server:
  httproute:
    enabled: true
    hostnames:
      - argocd.k8s1.christiank.dev
  grpcroute:
    enabled: true
    hostnames:
      - argocd.k8s1.christiank.dev
  backendTLSPolicy:
    enabled: true
