apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: k8s1
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - git:
        repoURL: https://github.com/ck0ne9000/iac
        revision: main
        files:
          - path: gitops/k8s1/*/*/definition.yaml
        values:
          type: '{{ index (splitList "/" .path.path) 2 }}'
          application: '{{ index (splitList "/" .path.path) 3 }}'
  strategy:
    type: RollingSync
    rollingSync:
      steps:
        - matchExpressions:
            - key: type
              operator: In
              values:
                - infrastructure
  template:
    metadata:
      name: "{{ .values.application }}"
      labels:
        type: "{{ .values.type }}"
    spec:
      project: default
      sources:
        - repoURL: "{{- .repository }}"
          chart: "{{ .chartName }}"
          targetRevision: "{{- .chartVersion }}"
          helm:
            releaseName: "{{ .values.application}}"
            valueFiles:
              - "$values/gitops/k8s1/{{.values.type}}/{{.values.application}}/values.yaml"
            ignoreMissingValueFiles: true
        - repoURL: https://github.com/ck0ne9000/iac
          targetRevision: main
          ref: values
          path: "gitops/k8s1/{{.values.type}}/{{.values.application}}"
      destination:
        name: in-cluster
        namespace: "{{ .values.application }}"
  templatePatch: |
    spec:
      syncPolicy:
        automated:
          prune: false
          selfHeal: true
        retry:
          limit: 5
          backoff:
            duration: 5s
            maxDuration: 3m0s
            factor: 2
        syncOptions:
          - CreateNamespace=true
      {{- if eq .serverSideApply "true"  }}
          - ServerSideApply=false
      {{- end }}
