apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: postgres-credentials
spec:
  refreshInterval: 1h0m0s
  secretStoreRef:
    name: oci-instance-principal
    kind: ClusterSecretStore
  target:
    name: keycloak-postgres-credentials
    creationPolicy: Owner
  dataFrom:
    - extract:
        key: keycloak-postgres-credentials
