apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-database
spec:
  instances: 3
  storage:
    pvcTemplate:
      metadata:
        labels:
          app: keycloak-database
      spec:
        storageClassName: oci-bv
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
  managed:
    roles:
      - name: keycloak
        ensure: present
        comment: keycloak user
        login: true
        superuser: false
        passwordSecret:
          name: keycloak-postgres-credentials
