apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: keycloak-database
spec:
  instances: 1
  storage:
    size: 1Gi
    storageClass: oci-bv
  managed:
    roles:
      - name: keycloak
        ensure: present
        comment: keycloak user
        login: true
        superuser: false
        passwordSecret:
          name: keycloak-postgres-credentials
